version: '3.8'
services:
  # Golang アプリケーションコンテナの設定
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: bookmap_backend
    volumes:
      - .:/go/src/app
    ports:
      - "8000:8000"
    networks:
      - dev_bookmap

networks:
  dev_bookmap:
    external: true