version: '3.8'
services:
  # PostgreSQL コンテナの設定
  db:
    image: postgres:15.4
    container_name: bookmap_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Golang アプリケーションコンテナの設定
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: bookmap_backend
    volumes:
      - .:/go/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db