openapi: 3.1.0
x-stoplight:
  id: stmcz64wt111f
info:
  title: bookmap
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/roadmaps:
    get:
      summary: Get All Roadmap
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roadmaps:
                    type: array
                    x-stoplight:
                      id: hyf5ae9ze5to6
                    items:
                      $ref: '#/components/schemas/Roadmap'
                      x-stoplight:
                        id: n7q6c1o4t90sj
              examples:
                Example 1:
                  value:
                    roadmaps:
                      - id: string
                        title: string
      operationId: get-api-roadmaps
      x-stoplight:
        id: w09zzh0s2ek9n
      description: ''
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: qgtjrgs4wufuh
        firstName:
          type: string
          x-stoplight:
            id: m50otxnjr854m
        lastName:
          type: string
          x-stoplight:
            id: pbxvau01g6w71
        email:
          type: string
          format: email
          x-stoplight:
            id: amrg9kwqi45rl
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: viaxv2bm535pf
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: qbpd86ek09u33
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: e9jfirubb4ke1
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: cf9o44lz93ysz
    Roadmap:
      title: Roadmap
      x-stoplight:
        id: lxc9x48ipuhub
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: 0lonlwav96kmx
        title:
          type: string
          x-stoplight:
            id: vj5f8wytrxhfa
